apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-docker-app
  labels:
    app: python-docker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-docker-app
  template:
    metadata:
      labels:
        app: python-docker-app
    spec:
      containers:
      - name: python-container
        image: jagadeesreddy/pythontest:latest
        ports:
        - containerPort: 5000  # Adjust this if your app uses another port
        env:
        - name: ENV
          value: "production"  # Example environment variable
