apiVersion: v1
kind: Service
metadata:
  name: python-docker-service
spec:
  selector:
    app: python-docker-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000  # Matches containerPort in deployment
  type: ClusterIP  # Change to LoadBalancer for external access if needed
